branches:
  only:
  - dev

language: node_js
node_js:
- stable

notifications:
  email: false

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: dev
  script: bash deploy.sh